// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Machine-readable error categories.
enum ErrorCode {
  validation,
  notFound,
  conflict,
  schemaVersion,
  git,
  io,
  permission,
  internal,
  ;
}

/// A structured project error (maps to a Dart exception via FRB).
class ProjectError implements FrbException {
  final ErrorCode code;
  final String message;

  const ProjectError({
    required this.code,
    required this.message,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
