// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_binder_nodes`, `collect_node_recursive`, `list_json_ids`, `map_commit_diff`, `map_merge_result`, `map_resolution`, `safe_component`

/// Opens an existing `.nov` project and returns its manager.
ProjectManager openProject({required String path}) =>
    RustLib.instance.api.crateApiManagerOpenProject(path: path);

/// Creates the empty directory skeleton of a `.nov` project (no file content —
/// Dart writes that).
void createProjectSkeleton({required String path}) =>
    RustLib.instance.api.crateApiManagerCreateProjectSkeleton(path: path);

/// Writes the standard internal `.gitignore`.
void writeGitignore({required String path}) =>
    RustLib.instance.api.crateApiManagerWriteGitignore(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProjectManager>>
abstract class ProjectManager implements RustOpaqueInterface {
  /// No-op (kept for symmetry; Dart drops the handle to release resources).
  Future<void> close();

  Future<void> deleteExport({required String id});

  Future<void> deleteFile({required String relativePath});

  Future<void> deleteFormat({required String id});

  Future<void> deleteLayout({required String id});

  /// Removes the physical `files/<id>/` directory. The binder is updated by
  /// Dart (via `write_binder`) after this call.
  Future<void> deleteNodeFiles({required String id});

  Future<void> deleteSession({required String date});

  Future<void> deleteStyle();

  /// Diffs two Quill deltas (JSON op arrays) and returns the result delta (JSON).
  Future<String> diffDelta(
      {required String beforeJson, required String afterJson});

  /// Aborts the current merge.
  Future<String> gitAbortMerge();

  /// Creates a branch from HEAD.
  Future<String> gitBranchCreate({required String name});

  /// Creates a branch from a specific commit oid.
  Future<String> gitBranchCreateFromCommit(
      {required String name, required String commitOid});

  /// Deletes the branch named [name]; [force] drops unmerged branches.
  Future<String> gitBranchDelete({required String name, required bool force});

  /// Merges the branch named [name] into the current branch (JSON `MergeResult`).
  Future<String> gitBranchMerge({required String name});

  /// Switches to the branch named [name].
  Future<String> gitBranchSwitch({required String name});

  Future<String> gitBranches();

  /// Checks out a branch, tag, or commit.
  Future<String> gitCheckout({required String target});

  /// Stages all changes and commits with the given author (`GitCredentials` JSON).
  Future<String> gitCommit(
      {required String message, required String authorJson});

  /// Detects every merge conflict (JSON array of conflict info).
  Future<String> gitConflictDetect();

  /// Finishes the conflict resolution (clears the conflict state).
  Future<String> gitConflictFinish();

  /// Resolves every conflicted file with the same resolution (`resolution_json`).
  Future<String> gitConflictResolveAll({required String resolutionJson});

  /// Returns the current branch name (JSON `{ "name": … }`).
  Future<String> gitCurrentBranch();

  /// Returns the diff between two commits (old oid, new oid) or `null`.
  Future<String> gitDiffBetweenCommits(
      {required String oldOid, required String newOid});

  /// Diffs two document nodes by uuid (`TreeDiff` JSON or `null`).
  Future<String> gitDiffDocuments(
      {required String oldUuid, required String newUuid});

  /// Diffs two JSON-serialized document trees (structural `TreeDiff` JSON),
  /// or `null` when the payloads cannot be read as documents.
  Future<String> gitDiffJsonDocuments(
      {required String oldJson, required String newJson});

  /// Fetches from the remote (default `origin`) using [credentials_json].
  Future<String> gitFetch(
      {required String remoteName, required String credentialsJson});

  /// Initializes the internal git repository of the project (no-op when it
  /// already exists).
  Future<String> gitInit();

  /// Returns the diff introduced by the last commit of [branch] (or `null`).
  Future<String> gitLastCommitDiff({required String branch});

  Future<String> gitLog({required int maxCount});

  /// Pulls a branch from `origin`, returning the merge result (JSON).
  Future<String> gitPull(
      {required String branch, required String credentialsJson});

  /// Pushes a branch to `origin`.
  Future<String> gitPush(
      {required String branch, required String credentialsJson});

  /// Returns the URL of the remote named [name] (JSON `{ "url": … | null }`).
  Future<String> gitRemoteUrl({required String name});

  /// Lists the configured remotes with their URLs (JSON array).
  Future<String> gitRemotes();

  /// Resolves a single conflicted file (`resolution_json` = `ConflictResolutionDto` JSON).
  Future<String> gitResolveConflict(
      {required String path, required String resolutionJson});

  /// Sets (adds or replaces) the URL of the remote named [name].
  Future<String> gitSetRemote({required String name, required String url});

  Future<String> gitStatus();

  Future<List<String>> listExports();

  Future<List<String>> listFiles({required String dir});

  Future<List<String>> listFormats();

  Future<List<String>> listLayouts();

  /// Lists writing sessions (history) by date file stem.
  Future<List<String>> listSessions();

  /// Project root path.
  Future<String> path();

  Future<String?> readBackup();

  Future<String?> readBinder();

  Future<String?> readCorkboard();

  Future<String?> readExport({required String id});

  Future<String?> readFile({required String relativePath});

  Future<String?> readFormat({required String id});

  Future<String?> readIcon();

  Future<String?> readLayout({required String id});

  Future<String?> readMetadata();

  Future<String?> readNodeComments({required String id});

  Future<String?> readNodeContent({required String id});

  Future<String?> readNodeNotes({required String id});

  Future<String?> readNodeSynopsis({required String id});

  /// The persisted search index (read-only; rebuilt via `reindex_search`).
  Future<String?> readSearch();

  Future<String?> readSections();

  Future<String?> readSession({required String date});

  Future<String?> readStyles();

  Future<String?> readTarget();

  /// Rebuilds the search index by reading the binder structurally and persisting
  /// `search.index.json`. Returns the index status (JSON).
  Future<String> reindexSearch();

  /// Searches (`mode` = `"quick"` or `"full"`), returning a JSON array of matches.
  Future<String> search(
      {required String query,
      required String optionsJson,
      required String mode});

  /// Current search-index status (JSON).
  Future<String> searchStatus();

  /// Creates a zip snapshot and returns its metadata (JSON).
  Future<String> snapshotCreate({required int version});

  /// Deletes a stored snapshot by id.
  Future<String> snapshotDelete({required String snapshotId});

  /// Lists stored snapshots (JSON array, newest first).
  Future<String> snapshotList();

  /// Restores a snapshot over the project (overwrites files).
  Future<String> snapshotRestore({required String snapshotId});

  /// Runs structural validation and returns a JSON array of issues.
  Future<String> validate();

  Future<void> writeBackup({required String json});

  Future<void> writeBinder({required String json});

  Future<void> writeCorkboard({required String json});

  Future<void> writeExport({required String id, required String json});

  Future<void> writeFile(
      {required String relativePath, required String contents});

  Future<void> writeFormat({required String id, required String json});

  Future<void> writeIcon({required String json});

  Future<void> writeLayout({required String id, required String json});

  Future<void> writeMetadata({required String json});

  Future<void> writeNodeComments({required String id, required String json});

  Future<void> writeNodeContent({required String id, required String json});

  Future<void> writeNodeNotes({required String id, required String text});

  Future<void> writeNodeSynopsis({required String id, required String json});

  Future<void> writeSections({required String json});

  Future<void> writeSession({required String date, required String json});

  Future<void> writeStyles({required String json});

  Future<void> writeTarget({required String json});
}
